### ISSUE TITLE
Why are you hosting my plugins?

### ISSUE THREAD

**Issue by Lunatixz** [kodil/kodil#1]
Please remove PseudoTV Live and any other Lunatixz Plugins
Its okay to host my repository, but not my plugins...

**Comment by kodil** [comment]
Hi , i donot modify or take credit for your plugin , we do it only to make the life of our ordinary non techi users lives easir (dont have to install too much repos ) , i wil appreciate it very much if you allow us to redistribute you plugin via our repo (btw it updates automatically) , how ever i will remove it and keep only your repo if you insist . but as i said we donot take credit or mdify the zip at all . also i donot gain anything from it . we do it as i said to make the life of our users easier (including my family which was the reason why we started to make this repo) . 
any way thank you for your hard work developing these plugins. 
thanks .

**Comment by Lunatixz** [comment]
it's not a matter of allowing, You are causing conflicts with my plugins... Kodi plugins are not meant to be shared between multiple repos (one of the reasons superrepo is not well received by developers). 

I kindly ask you remove any of my plugins, and only provide my repository. I understand what you are trying to do for your users, but its causing issues you are not aware of...

**Comment by kodil** [comment]
ok i will remove it , 
but can you explain what issues are they causing , i wasnt aware of any issues generated by the usage of multiple repos with multiple addons . 
thanks.

**Comment by Lunatixz** [comment]
Kodi sees both of our repos as a host for plugins, if I push code and you didn't update your repo yet == conflict.

**Comment by kodil** [comment]
actually i added ur repo just yesterday . but it you revert code are u updating the version of ur plugin ? 
my repo updates every hour so it should have been only visible for maximum of an hour . 
also if two repos display the same addon ID and one is newer kodi does not show conflict it just selects the newst addon . 
what i think could have been was i did an upgrade yesterday to my addon yesterday so it was not updating for most of the time . thats why users  might have been longer on the old version . 
as for the repos themslef  if i remove all the addons , that would defeat the purpose .

**Comment by Lunatixz** [comment]
I think you are confused... I'm telling you there is a conflict, you can run off on any tangent you believe fits your defense... the end result is two plugins with the same id can't be shared by more then one repository...

The purpose should be to do what is best for your users, and that would be to only include repositories and not the plugins. You are not the developer, you should not hijack other developers plugins via a second repository... you are unaware of the damage and conflicts you are causing. Its a disservice to the community and to Kodi... The responsible thing would be to share repositories .

**Comment by kodil** [comment]
Its not a matter of belife , i went over the xbmc code , its scan every repo and build an update list with the id as key and than updates the source based on versioning , it supports multiple repos with same addon id , actually they did a good job of resolving duplicates by

**Comment by Lunatixz** [comment]
bad perception of you? I don't know you... Haven't even considered you personally. Like I said I found you because I tracked down who was pushing updates to my plugins... You absolutely can not host one plugin from two repos. Either you respect my request to remove and only host my repo or not.

**Comment by biglad** [comment]
PLEASE REMOVE ALL CEREBRO ADDONS
