### ISSUE TITLE
Update Skin Shortcuts

### ISSUE THREAD

**Issue by Ignoble61** [kodil/kodil#2]
The version of Skin Shortcuts you have on your repository - 0.6.5 - has a bug in it. Can you please update ASAP to the latest git version (0.6.6) - https://github.com/BigNoid/script.skinshortcuts.

Much appreciated :)

**Comment by kodil** [comment]
Hi my repo updates automatically from your repo . every 6 hours , but i ran the update now . its already up now .

**Comment by Ignoble61** [comment]
That's hugely appreciated :)

**Comment by kodil** [comment]
thanks for the head up

**Comment by Ignoble61** [comment]
Are you aware that Git is where development happens, and it's quite possible (as happened here) for git to be non-working?

Truth be we do try to avoid this, obviously, and the truth is we wouldn't have found the issue with 0.6.5 if you guys hadn't pushed it ahead of it reaching the official Kodi repo - and let me thank you for that, because of that this may be the first time we update the script on the official repo without a major bug! - but it's been 5 minor revisions between versions, and bugs have been introduced (and fixed) as development has happened...

**Comment by kodil** [comment]
i am aware of git's intended use . but as a production platform its very stable , more than most hosting sites i worked with . 
kodi default update interval for updates is 6 hours i try to keep our update time shorter , but in ur case im updating from ur repo in github . 
by the way thanks for the addon i use it myself and it saves me alot of time . :)

**Comment by Ignoble61** [comment]
I'm very glad you find it useful :)

Can I suggest you check that your 6-hour update is working correctly. The commit which introduced the error was pushed 8 days ago - we got the first report of any issues yesterday. If it really is updated at 6-hourly intervals, and with the amount of people who have reported the issue, that's a hell of a long time from the issue being introduced to it being reported :)

**Comment by kodil** [comment]
yeah i moved the updating system from the first of the month , as i was moving appartment   and had to shutdown my servers . i brought everything up to aws instance yesterday , thats why the gap . 
btw my repo is suppose to be for a small community in israel not too savy , i wonder how and who opened the issue , as i thought only a limited ammount of people use my repo

**Comment by Ignoble61** [comment]
That's understandable, IT systems are never stable from one minute to the next, especially when updating :)

For reference, we found out primarily because of this thread - http://forum.kodi.tv/showthread.php?tid=244939 - though there have been at least two other threads opened elsewhere on the forums and the issue reported in the official Skin Shortcuts thread. Don't underestimate how many people use your repo :)

(And, from the comments in the thread I linked to, it would seem there's at least one person selling Kodi boxes with your repo pre-installed!)

Again, though, thanks for helping track down the bug before we got it into the official Kodi repo - the fallout would have been a hell of a lot worse!

As it it, as you've updated on your repo (and we'll be pushing the fixed version to the official repo soon) I'll happily close this issue, and thank you once again for your responsiveness.

**Comment by kodil** [comment]
thanks . and as it will allow for faster updates i increased the rate of update in my repo to once an hour. 
thanks for the update . 
glad i could be of some help .

**Comment by Ignoble61** [comment]
Can I advise against an hourly update? :)

As said, you're pulling from Git where development takes place, and bugs _will_ occur. Whilst an hourly pull means that when issues are found and fixed, they will be additionally fixed on your repo shortly afterwards, it also means that when issues are pushed but AREN'T fixed immediately, the bugged version will inevitably get pushed to your repo (and, after recent experiences, I think its fair to say we'll be directing people with problems to you!)

Can I suggest that you only pull changes to the script if there are any skins on your repo which actually require such changes, and then a six-hourly pull seems appropriate as that gives us time when - as happens - we discover something has been pushed which creates issue, and means (dependant on the interval of the six-hourly-pull) we may have time to fix it before it creates issues for more users than you realised you have ;)

**Comment by kodil** [comment]
i dont remember adding the git url for your plugin . 
i am pulling it from another repo , if it is a beta indeed i will pull it from the repo , but i dont see the need to pull from official kodi repo thats already pre installed , i suspect i grabbed it from a specific skin repo that pulls ur beta's. 

after close investigation i have no reference specific to your git 
i will dig in the logs for the repo updates and check where i pulled it from . 
thanks again for the info .

**Comment by kodil** [comment]
i tracked the update to a skinner who uses ur addon in his skin , 
he has the version 0.6.6 in his repo , thats how i got it . 
as i said i try not to pull from github but from other repos's 
thanks il talk to him the repo he has is called abeksis
