### ISSUE TITLE
mobpro video plugin not working

### ISSUE THREAD

**Issue by WebsliceNL** [kodil/kodil#4]
Hi,

Trying get Kodi/Mobpro working on Linux Fedora 24.

Initially started here:

http://koditips.com/kodi-mobdro-install-guide-popular-iptv-option/

after installing the repo, installing mobpro from the repo gave an installation error.

Looking in to the logs, it was trying to install a non existing 1.0.5 version from github.

Then I tried installing the available 1.0.6 version zip file.
It installed, but all options "channels, news, etc" give a Mobpro error.

In the logs I see Python error: No JSON object could be decoded.

Gr, J

**Comment by mikiha** [comment]
this plugin is not developed any more sincemobdro encrypted their json
