### ISSUE TITLE
New addon for reshet website

### ISSUE THREAD

**Issue by Fishenzon** [kodil/kodil#9]
Hi.
You can see my new addon for reshet website:
https://github.com/Fishenzon/My/raw/master/plugin.video.reshet-1.0.1.zip

**Comment by KodiKid** [comment]
You addon 1.0.1/2 for reshet is not working.

**Comment by ebs111** [comment]
hi
there is a new subtitle addon for all four sites:
subscenter
subscene
wizdom
opensubtitles

https://github.com/ebs111/service.subtitles.All_Subs/blob/master/service.subtitles.All_Subs-1.0.7.zip

and for reshetTV
https://github.com/ebs111/service.subtitles.All_Subs/blob/master/plugin.video.reshet.ebs.video-1.2.0.zip
